"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" XDG Base Directory {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if !has('nvim') && has('patch-9.1.0327')
    let $XDG_CONFIG_HOME = !empty($XDG_CONFIG_HOME) ? $XDG_CONFIG_HOME : $HOME . '/.config'
    let $XDG_DATA_HOME   = !empty($XDG_DATA_HOME)   ? $XDG_DATA_HOME   : $HOME . '/.local/share'
    let $XDG_STATE_HOME  = !empty($XDG_STATE_HOME)  ? $XDG_STATE_HOME  : $HOME . '/.local/state'
    let $XDG_CACHE_HOME  = !empty($XDG_CACHE_HOME)  ? $XDG_CACHE_HOME  : $HOME . '/.cache'
    set runtimepath^=$XDG_DATA_HOME/vim
    set runtimepath+=$XDG_DATA_HOME/vim/after
    set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
    set packpath+=$XDG_DATA_HOME/vim/after,$XDG_CONFIG_HOME/vim/after
    set viminfofile=$XDG_STATE_HOME/vim/viminfo
    set undodir=$XDG_STATE_HOME/vim/undo
    " Trailing // tells vim to use the full file path in swap/backup filenames,
    " preventing collisions when editing files with the same name in different dirs.
    set directory=$XDG_CACHE_HOME/vim/swap//
    set backupdir=$XDG_CACHE_HOME/vim/backup//
    set viewdir=$XDG_CACHE_HOME/vim/view
    silent! call mkdir(&undodir,   'p', 0700)
    silent! call mkdir(&directory, 'p', 0700)
    silent! call mkdir(&backupdir, 'p', 0700)
    silent! call mkdir(&viewdir,   'p', 0700)
endif
" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Automatic installation of vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : (has('patch-9.1.0327') ? $XDG_DATA_HOME . '/vim' : '~/.vim')
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -sS -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

if empty(glob(data_dir . '/after/syntax/sh/slurm.vim'))
  silent execute '!curl -sS -fLo '.data_dir.'/after/syntax/sh/slurm.vim --create-dirs https://raw.githubusercontent.com/SchedMD/slurm/refs/heads/master/contribs/slurm_completion_help/slurm.vim'
endif

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'vim-scripts/restore_view.vim'     " automatically save and restore view

" Plugin snipmate and its dependencies
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'
Plug 'honza/vim-snippets'

Plug 'majutsushi/tagbar'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'          " show git status in nerdtree
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-rails'
Plug 'leafgarland/typescript-vim'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-scripts/a.vim'                                " Quickly switch between source files and header files
Plug 'vim-scripts/minibufexplorerpp'                    " Manage buffer
"Plug 'Valloric/YouCompleteMe'
Plug 'Valloric/ListToggle'                  " A simple vim plugin for toggling the display of the quickfix list and the location-list
Plug 'vim-scripts/DrawIt'
Plug 'tkhoa2711/vim-togglenumber'
Plug 'luochen1990/rainbow'
Plug 'tmhedberg/SimpylFold'                 " Fold python code more precise
"Plug 'winmanager'                          " Manager windows, combind NERDtree and taglist
"Plug 'terryma/vim-multiple-cursors'
"Plug 'vim-scripts/loremipsum'              " Placeholder for frontpage development
"Plug 'benmills/vimux'                       " make interacting with tmux from vim effortless
Plug 'airblade/vim-gitgutter'               " shows a git diff in the 'gutter' (sign column).
Plug 'tpope/vim-fugitive'                   " git integration, used for branch name in statusline
Plug 'ntpeters/vim-better-whitespace'       " highlight and strip trailing whitespace
Plug 'noahfrederick/vim-skeleton'           " populate new files from skeleton templates

" Theme
"Plug 'altercation/vim-colors-solarized'

" plug#end() automatically executes filetype plugin indent on and syntax enable
call plug#end()
" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General Settings {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syntax on
" allow switching buffers without saving
set hidden
" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed
" read/write a .viminfo file, don't store more
"set viminfo='20,\"50
" Enable mouse in all modes
"set mouse=a
" Disable error bells
set noerrorbells
" Use visual bell instead of beeping.
set visualbell
" Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure
" Allow specified keys that move the cursor left/right to move to the previous/next line when the cursor is on the first/last character in the line.
set whichwrap=b,s,<,>,[,]
" Don't show the intro message when starting Vim
"set shortmess=atI
" Don't create backups when editing files in certain directories
set backupskip=/tmp/*,/private/tmp/*
" set status line
set statusline=
set statusline+=%{BufStatus()}%f
set statusline+=\ [
set statusline+=%{empty(&ft)?'none':&ft},
set statusline+=%{empty(&fileencoding)?&encoding:&fileencoding},
set statusline+=%{&fileformat}]
set statusline+=%{GitBranch()}
set statusline+=%1*%h%m%r%w%q%0*
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%=
set statusline+=%-12.(%l:%c%V%)\ %P

" Don't reset cursor to start of line when moving around.
set nostartofline
" Show the (partial) command as it's being typed
set showcmd
"set rulerformat=%20(%2*%<%f%=\ %m%r\ %3l\ %c\ %p%%%)
" Number of screen lines to use for the command-line.  Helps avoiding
"set cmdheight=2
" Show the filename in the window titlebar
set title

" Use UTF-8 without BOM, used inside Vim
set encoding=utf-8 nobomb
set fencs=utf-8,ucs-bom,cp936,gb18030,big5,euc-jp,euc-kr,latin1
" Set vim available to read binary file. You can also use the -b Vim argument.
"set binary
" Don't add empty newlines at the end of files
"set noeol
" When open binary files, display the values by hex
set display+=uhex
" Respect modeline in files.
set modeline
set modelines=4

" Change mapleader
let mapleader=","
" Allow cursor keys in insert mode
set esckeys
" timeout for map keys
set timeoutlen=1000
" timeout for terminal escape sequences
set ttimeoutlen=100
" Use F9 to toggle paste mode
set pastetoggle=<F9>

" Highlight searches
set hlsearch
" Ignore case of searches
set ignorecase
" Make search case sensitive when search content contains upper case
set smartcase
" Add the g flag to search/replace by default
"set gdefault
" Highlight the matched brackets
set showmatch
" Highlight setting for cursorline
hi CursorLine cterm=NONE ctermbg=darkgrey ctermfg=NONE guibg=darkgrey guifg=NONE
hi User1 ctermbg=black ctermfg=white guibg=black guifg=white
" Highlight current line
set cursorline

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
"set smartindent  " superseded by cindent; handled by filetype plugins
"set cindent      " can misbehave on non-C files (e.g. de-dents # in Python)
set wrap
" Start scrolling three lines before the horizontal window border
"set scrolloff=3
" Enable relative line numbers
set number
set relativenumber
" Show invisible characters
set listchars=tab:▸\ ,trail:·,eol:¬,nbsp:_
"set list
" fold method
"set fdm=marker
set foldmethod=indent
" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Functions {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


function! BufStatus()
    let total = len(getbufinfo({'buflisted': 1}))
    return total > 1 ? '[' . bufnr('%') . '/' . total . '] ' : ''
endfunction

function! GitBranch()
    let branch = FugitiveHead()
    return empty(branch) ? '' : '[' . branch . '] '
endfunction

function! RemoveCR()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    :%s/
//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfunction

function! Compile()
    write
    if &filetype == "c"
        !gcc -Wall % -o %< && ./%<
    elseif &filetype == "cpp"
        !g++ -Wall % -o %< && ./%<
    endif
endfunction

function! ToggleTextwidth()
    if &textwidth == 76
        set textwidth=0
        echo 'textwidth=0'
    else
        set textwidth=76
        echo 'textwidth=76'
    endif
endfunction

function! SetTab()
    if &filetype == "ruby" || &filetype == "eruby" || &filetype == "html"
        set tabstop=2 shiftwidth=2 softtabstop=2
    else
        set tabstop=4 shiftwidth=4 softtabstop=4
    endif
endfunction

" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" autocmd {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set Tab format depends on file types
autocmd BufNewFile,BufRead * call SetTab()
" Remove comment leader when joining lines (run after filetype plugins)
autocmd FileType * setlocal formatoptions+=j

" Do not highlight the current line when entering insert mode
autocmd InsertEnter * setlocal nocursorline
" Do not highlight the current line when leaving the current window
autocmd WinLeave * setlocal nocursorline
" Highlight the current line after leaving insert mode
autocmd InsertLeave * setlocal cursorline
" Highlight the current line after entering a new window
autocmd WinEnter * setlocal cursorline
" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Map {{{
" Check the key description: :h key-notation
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
nnoremap <space> za

noremap <leader>ss :StripWhitespace<CR>
noremap <leader>cr :call RemoveCR()<CR>
" Save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>
" Close highlight
nnoremap <leader><CR> :nohlsearch<CR>
" Toggle MiniBufExplorer
nnoremap <leader>b :TMiniBufExplorer<CR>
" Toggle NERDTree
noremap <leader>tr :NERDTreeToggle<CR>
" Toggle tagbar
noremap <leader>tb :TagbarToggle<CR>
" Toggle set list
noremap <leader>ls <ESC>:set invlist<CR>
" Toggle textwidth
noremap <leader>tw <ESC>:call ToggleTextwidth()<CR>
noremap <leader>n :ToggleNumber<CR>
noremap <leader>r :RainbowToggle<CR>

" Move between different Tabs
"nnoremap <leader>t1 1gt
"nnoremap <leader>t2 2gt
"nnoremap <leader>t3 3gt
"nnoremap <leader>t4 4gt
"nnoremap <leader>t5 5gt
"nnoremap <leader>t6 6gt
"nnoremap <leader>t7 7gt
"nnoremap <leader>t8 8gt
"nnoremap <leader>t9 9gt

" Move between different Buffers
nnoremap <leader>1 :b1<CR>
nnoremap <leader>2 :b2<CR>
nnoremap <leader>3 :b3<CR>
nnoremap <leader>4 :b4<CR>
nnoremap <leader>5 :b5<CR>
nnoremap <leader>6 :b6<CR>
nnoremap <leader>7 :b7<CR>
nnoremap <leader>8 :b8<CR>
nnoremap <leader>9 :b9<CR>

" Move between different windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Resize window size
noremap + <C-w>+
noremap - <C-w>-
noremap <C-n> <C-w><
noremap <C-m> <C-w>>

"inoremap <F5> <ESC>:call Compile()<CR>
noremap <F5> <ESC>:call Compile()<CR>
" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Theme {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if has('gui_running')
    set background=light
else
    set background=dark
endif

" }}}

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"------------------------------------
" tagbar settings {{{
"------------------------------------
let g:tagbar_width = 30
let g:tagbar_zoomwidth = 0
let g:tagbar_autofocus = 1
let g:tagbar_sort = 0
let g:tagbar_previewwin_pos = 'botright'
" }}}

"------------------------------------
" syntastic settings {{{
" Checkers: shell (http://www.shellcheck.net/about.html)
"------------------------------------

let g:syntastic_stl_format = "[%E{Err: %fe #%e}%B{, }%W{Warn: %fw #%w}]"
let g:syntastic_error_symbol = "✗"
let g:syntastic_warning_symbol = "⚠"
let g:syntastic_style_error_symbol = "S>"
let g:syntastic_style_warning_symbol = "S!"
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height = 5
let g:syntastic_cpp_compiler = "g++"
let g:syntastic_cpp_compiler_options = " -std=c++11 -stdlib=libc++ -Wall"
let g:syntastic_c_compiler = "gcc"
let g:syntastic_c_compiler_options = " -Wall -pedantic-errors"
" }}}

"------------------------------------
" MiniBufExplorer settings {{{
"------------------------------------
let g:miniBufExplSplitToEdge = 0
let g:miniBufExplModSelTarget = 1
let g:miniBufExplorerMoreThanOne = 3
" }}}

"------------------------------------
" Rainbow settings {{{
" highlight Parentheses
"------------------------------------
let g:rainbow_conf = {
    \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
    \   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
    \   'operators': '_,_',
    \   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
    \   'separately': {
    \       '*': {},
    \       'tex': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
    \       },
    \       'lisp': {
    \           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
    \       },
    \       'vim': {
    \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
    \       },
    \       'html': {
    \           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
    \       },
    \       'css': 0,
    \   }
    \}
" }}}

"------------------------------------
" nerdtree settings {{{
"------------------------------------
" Close nerdtree windows when all other windows are closed
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" }}}

"------------------------------------
" nerdtree-git-plugin settings {{{
"------------------------------------
let g:NERDTreeGitStatusIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
    \ }
" }}}

"------------------------------------
" ListToggle settings {{{
"------------------------------------
let g:lt_location_list_toggle_map = '<leader>lo'
let g:lt_quickfix_list_toggle_map = '<leader>qu'
" }}}

"------------------------------------
" vim-better-whitespace settings {{{
"------------------------------------
let g:better_whitespace_enabled = 1
" }}}

"------------------------------------
" vim-skeleton settings {{{
"------------------------------------
let g:skeleton_template_dir = expand('<sfile>:p:h') . '/skeletons'
" }}}

" }}}

" vim:ft=vim:fdm=marker:ff=unix:nowrap:tabstop=4:shiftwidth=4:softtabstop=4:smarttab:shiftround:expandtab
